// Maintainer-only capture of the real local demo; no production account or URL.
import { chromium, expect } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout as delay } from "node:timers/promises";
import { promisify } from "node:util";
import { fixture, login } from "./runtime.mjs";

const output = fileURLToPath(new URL("../../docs/media/", import.meta.url));
const execute = promisify(execFile);
const encoder = process.env.REVIEW_TUNNEL_MEDIA_FFMPEG ?? "ffmpeg";
await execute(encoder, ["-version"]);
const temporary = await mkdtemp(join(tmpdir(), "review-tunnel-media-"));
const demo = await fixture();
const browser = await chromium.launch({ channel: "chrome" });
let recorded;
try {
  await mkdir(output, { recursive: true });
  const ready = await demo.start();
  // Authenticate before recording. Cookie state stays in memory and is never an artifact.
  const authentication = await browser.newContext();
  const signIn = await authentication.newPage();
  await login(signIn, ready.shareUrl, ready.accounts.reviewer);
  await expect(signIn.getByRole("heading", { name: "A calmer way to launch." })).toBeVisible();
  const state = await authentication.storageState();
  await authentication.close();
  const developerContext = await browser.newContext();
  const developer = await developerContext.newPage();
  await login(developer, `${ready.controlUrl}/reviews`, ready.accounts.developer);
  const viewport = { width: 1440, height: 960 };
  recorded = await browser.newContext({ viewport, storageState: state, recordVideo: { dir: temporary, size: viewport } });
  const videoStarted = Date.now();
  const page = await recorded.newPage();
  await page.goto(ready.shareUrl);
  await expect(page.getByRole("heading", { name: "A calmer way to launch." })).toBeVisible();
  const overlay = page.locator("review-tunnel-overlay");
  await expect(overlay.getByRole("button", { name: "Select area or pin" })).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: join(temporary, "loaded.png") });
  const trimBefore = (Date.now() - videoStarted) / 1000 + .2;
  await delay(1500);
  const card = page.locator('[data-review-id="launch-card"]');
  const box = await card.boundingBox();
  await overlay.getByRole("button", { name: "Select area or pin" }).click();
  await page.mouse.move(box.x + box.width * .12, box.y + box.height * .1);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * .85, box.y + box.height * .4, { steps: 16 });
  await page.mouse.up();
  await delay(800);
  await overlay.getByRole("textbox", { name: "Comment", exact: true }).pressSequentially("@developer Could this card have a little more breathing room?", { delay: 25 });
  await overlay.getByRole("button", { name: "Comment", exact: true }).click();
  const thread = overlay.locator(".thread").filter({ hasText: "Could this card" });
  await expect(thread).toBeVisible();
  const permalink = await thread.getByRole("link", { name: "Permanent link" }).getAttribute("href");
  await page.screenshot({ path: join(output, "pinned-review.png") });
  await delay(1800);
  await overlay.getByRole("button", { name: "Close review panel" }).click();
  await page.getByRole("button", { name: "Try compact layout" }).click();
  await delay(1200);
  await overlay.getByRole("button", { name: "Open review panel" }).click();
  await developer.goto(permalink);
  await developer.getByRole("textbox", { name: "Reply to comment" }).fill("Spacing updated. Ready for another look.");
  await developer.getByRole("button", { name: "Reply", exact: true }).click();
  await expect(developer.locator(".reply")).toContainText("Spacing updated");
  await developer.getByRole("button", { name: "Request review", exact: true }).click();
  await expect(thread.locator(".thread-status")).toHaveText("Needs review");
  await delay(1500);
  await page.screenshot({ path: join(output, "needs-review.png") });
  await page.goto(permalink);
  await expect(page.locator(".thread-status")).toHaveText("Needs review");
  await page.locator("#inbox summary").click();
  await expect(page.locator("#notifications")).toContainText("답글을 남겼습니다");
  await delay(1800);
  await page.getByRole("button", { name: "Confirm resolved", exact: true }).click();
  await expect(page.locator(".thread-status")).toHaveText("Resolved");
  await page.locator(".history summary").click();
  await expect(page.locator(".history")).toContainText("NEEDS_REVIEW → RESOLVED");
  await delay(1800);
  await page.screenshot({ path: join(output, "review-inbox.png") });
  const video = page.video();
  await recorded.close(); recorded = undefined;
  const rawVideo = join(temporary, "raw.webm");
  await video.saveAs(rawVideo);
  await execute(encoder, ["-y", "-i", rawVideo, "-ss", String(trimBefore), "-an", "-c:v", "libvpx", "-b:v", "1500k", join(output, "review-flow.webm")]);
  await developerContext.close();
  await writeFile(join(output, "README.md"), `# Local demo media\n\nCaptured from the actual authenticated Vite example with synthetic local accounts and data.\n\n- [pinned-review.png](pinned-review.png): a region comment attached to the launch card.\n- [needs-review.png](needs-review.png): the pin follows the compact layout; a developer reply requests re-review.\n- [review-inbox.png](review-inbox.png): recipient notifications and completed processing history.\n- \`review-flow.webm\`: the same browser flow, captured after login; developer actions happen in a separate unrecorded browser.\n\nRegenerate from the repository root after \`npm ci\` and \`npm run build\`, with Chrome, FFmpeg (libvpx/WebM), and local Docker available:\n\n\`\`\`sh\nnode tests/demo/capture-media.mjs\n\`\`\`\n\nThe capture creates and deletes its own demo database. It replaces only these four named media files and this index. Inspect the resulting images/video before committing; cookie state is kept in memory and never saved. Only the initial loading interval is trimmed. Set REVIEW_TUNNEL_MEDIA_FFMPEG to an explicit FFmpeg executable when it is not on PATH.\n\nThe example and these original captures are covered by the repository's [MIT license](../../LICENSE). The recording illustrates product behavior and is not a performance benchmark.\n`);
  console.log("Captured three screenshots and one authenticated demo video using disposable local data.");
} finally {
  await recorded?.close();
  await browser.close();
  await demo.close();
  await rm(temporary, { recursive: true, force: true });
}
